apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: djust-theming
  namespace: djust-theming
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - theming.djust.org
    secretName: djust-theming-tls
  rules:
  - host: theming.djust.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: djust-theming
            port:
              number: 8000
