"""Mono -- Pure grayscale — zero chroma, maximum discipline."""

from ._base import (
    ColorScale,
    ThemePack,
    ThemePreset,
    ThemeTokens,
    ANIM_SMOOTH,
    ICON_MINIMAL,
    ILLUST_LINE,
    INTERACT_SUBTLE,
    PATTERN_DOTS,
)

# --- Color Preset ---

LIGHT = ThemeTokens(
    background=ColorScale(0, 0, 100),
    foreground=ColorScale(0, 0, 10),
    card=ColorScale(0, 0, 98),
    card_foreground=ColorScale(0, 0, 10),
    popover=ColorScale(0, 0, 98),
    popover_foreground=ColorScale(0, 0, 10),
    primary=ColorScale(0, 0, 15),
    primary_foreground=ColorScale(0, 0, 100),
    secondary=ColorScale(0, 0, 93),
    secondary_foreground=ColorScale(0, 0, 15),
    muted=ColorScale(0, 0, 93),
    muted_foreground=ColorScale(0, 0, 45),
    accent=ColorScale(0, 0, 90),
    accent_foreground=ColorScale(0, 0, 10),
    destructive=ColorScale(0, 0, 30),
    destructive_foreground=ColorScale(0, 0, 100),
    success=ColorScale(0, 0, 35),
    success_foreground=ColorScale(0, 0, 100),
    warning=ColorScale(0, 0, 40),
    warning_foreground=ColorScale(0, 0, 100),
    info=ColorScale(0, 0, 35),
    info_foreground=ColorScale(0, 0, 100),
    link=ColorScale(0, 0, 20),
    link_hover=ColorScale(0, 0, 10),
    code=ColorScale(0, 0, 94),
    code_foreground=ColorScale(0, 0, 25),
    selection=ColorScale(0, 0, 85),
    selection_foreground=ColorScale(0, 10, 15),
    brand=ColorScale(0, 0, 15),
    brand_foreground=ColorScale(0, 0, 100),
    border=ColorScale(0, 0, 82),
    input=ColorScale(0, 0, 82),
    ring=ColorScale(0, 0, 15),
    surface_1=ColorScale(0, 5, 96),
    surface_2=ColorScale(0, 5, 93),
    surface_3=ColorScale(0, 5, 90),
)

DARK = ThemeTokens(
    background=ColorScale(0, 0, 7),
    foreground=ColorScale(0, 0, 90),
    card=ColorScale(0, 0, 10),
    card_foreground=ColorScale(0, 0, 90),
    popover=ColorScale(0, 0, 10),
    popover_foreground=ColorScale(0, 0, 90),
    primary=ColorScale(0, 0, 85),
    primary_foreground=ColorScale(0, 0, 7),
    secondary=ColorScale(0, 0, 15),
    secondary_foreground=ColorScale(0, 0, 85),
    muted=ColorScale(0, 0, 15),
    muted_foreground=ColorScale(0, 0, 55),
    accent=ColorScale(0, 0, 18),
    accent_foreground=ColorScale(0, 0, 90),
    destructive=ColorScale(0, 0, 70),
    destructive_foreground=ColorScale(0, 0, 7),
    success=ColorScale(0, 0, 65),
    success_foreground=ColorScale(0, 0, 7),
    warning=ColorScale(0, 0, 60),
    warning_foreground=ColorScale(0, 0, 7),
    info=ColorScale(0, 0, 65),
    info_foreground=ColorScale(0, 0, 7),
    link=ColorScale(0, 0, 80),
    link_hover=ColorScale(0, 0, 95),
    code=ColorScale(0, 0, 13),
    code_foreground=ColorScale(0, 0, 70),
    selection=ColorScale(0, 0, 25),
    selection_foreground=ColorScale(0, 10, 90),
    brand=ColorScale(0, 0, 85),
    brand_foreground=ColorScale(0, 0, 7),
    border=ColorScale(0, 0, 20),
    input=ColorScale(0, 0, 20),
    ring=ColorScale(0, 0, 85),
    surface_1=ColorScale(0, 5, 6),
    surface_2=ColorScale(0, 5, 10),
    surface_3=ColorScale(0, 5, 14),
)

PRESET = ThemePreset(
    name="mono",
    display_name="Mono",
    description="Pure grayscale — zero chroma, maximum discipline",
    light=LIGHT,
    dark=DARK,
)

# --- Theme Pack ---

PACK = ThemePack(
    name="mono",
    display_name="Mono",
    description="Pure grayscale — zero chroma discipline",
    category="minimal",
    design_theme="minimalist",
    color_preset="mono",
    icon_style=ICON_MINIMAL,
    animation_style=ANIM_SMOOTH,
    pattern_style=PATTERN_DOTS,
    interaction_style=INTERACT_SUBTLE,
    illustration_style=ILLUST_LINE,
)
